### ISSUE TITLE
esde_load_sde fails with AttributeError: 'ItemMarketGroup' object has no attribute 'name_en' on fresh eve_sde install when upgrading from corptools 2.x to 3.0.0

### ISSUE THREAD

**Issue by Pallustris** [Solar-Helix-Independent-Transport/allianceauth-corp-tools#285]
Environment:

Alliance Auth: 5.0.1
allianceauth-corptools: 3.0.0
django-eveonline-sde: 0.0.1b9
Django: 5.2.14
django-esi: 9.2.0
django-modeltranslation: 0.19.17
Python: 3.12
MariaDB: 11.8.6
Installation type: Docker (bare metal likely affected too)

Description:
When upgrading from allianceauth-corptools 2.x to 3.0.0 on an existing Alliance Auth installation, eve_sde is a brand new dependency that didn't exist before. Running auth esde_load_sde to populate the SDE data fails consistently with:
`AttributeError: 'ItemMarketGroup' object has no attribute 'name_en'`
Steps to reproduce:

Start from an existing AA installation running corptools 2.x (no eve_sde previously installed)
Upgrade to corptools 3.0.0
Add 'eve_sde' to INSTALLED_APPS in local.py
Run auth migrate — all eve_sde migrations (0001–0018) apply successfully
Run auth esde_load_sde

What happens:
The command loads ItemCategory and ItemGroup successfully, then fails at ItemMarketGroup:
```
eve-sde/categories.jsonl - 48 Models from 48/48 Lines - New: 48 - Updates: 0
eve-sde/groups.jsonl - 1599 Models from 1599/1599 Lines - New: 1599 - Updates: 0
eve-sde/marketGroups.jsonl - 2095 Models from 2095/2095 Lines - New: 2095 - Updates: 0
eve-sde/marketGroups.jsonl - 2095 Models from 2095/2095 Lines - New: 0 - Updates: 2095
AttributeError: 'ItemMarketGroup' object has no attribute 'name_en'
```
Root cause analysis:
ItemMarketGroup has a custom load_from_sde in types.py that calls super().load_from_sde() twice — a deliberate two-pass approach to handle the self-referential parent_group_id FK:
```
@classmethod
def load_from_sde(cls, folder_name) -> None:
    # First pass without parent_group_id to avoid fkey issues
    setattr(cls.Import, "data_map", first_pass_data_map)
    super().load_from_sde(folder_name)
    # Second pass to update parent_group_id
    setattr(cls.Import, "data_map", original_data_map)
    super().load_from_sde(folder_name)
```
On the second pass, all 2095 records already exist in the database, so load_from_sde in base.py sends them all to _updates. The create_update method then fetches them from the database via cls.objects.filter() for comparison in is_equal:
```
_e = cls.objects.filter(id__in=[_i.pk for _i in update_model_list])
_checks = {}
for _i in _e:
    _checks[_i.pk] = _i
update_model_list = [_s for _s in update_model_list if not cls.is_equal(_s, _checks[_s.pk])]
```
The is_equal method then iterates over data_map fields and calls getattr(old, f) on the database-fetched objects. One of the fields in data_map is a translated field (name_en added by django-modeltranslation) which is not returned as a concrete attribute on plain queryset fetches, causing the AttributeError.
Additional complication — circular dependency on upgrade:
This bug also creates a deadlock when upgrading from corptools 2.x to 3.0.0:

corptools migration 0130_swap_to_eve_sde checks for an existing SDE record and fails with AttributeError: 'NoneType' object has no attribute 'last_check_date' if none exists
esde_load_sde requires all migrations to be complete (specifically the eve_sde_itemmarketgroup table must exist) before it can run
The only way to break the deadlock is to fake migration 0130 with --fake, but esde_load_sde then still fails as described above

What was tried:

Truncating eve_sde_itemcategory, eve_sde_itemgroup, and eve_sde_itemmarketgroup tables and retrying — same error
Running auth migrate eve_sde zero then auth migrate to fully reset eve_sde tables and retrying — same error
Faking migration corptools 0130 with --fake then running esde_load_sde — same error
No newer version of django-eveonline-sde is available on PyPI or via pip to upgrade to

Expected behaviour:
esde_load_sde should complete successfully on a fresh eve_sde installation when upgrading from corptools 2.x to 3.0.0.
Suggested fix:
In is_equal in base.py, use getattr(old, f, None) instead of getattr(old, f) to handle missing translated attributes gracefully. Alternatively, the second pass in ItemMarketGroup.load_from_sde could use only('pk', 'parent_group_id') when fetching existing records for comparison, since only parent_group_id is being updated in that pass.

**Comment by soratidus999** [comment]
You have missed a step in the upgrade instructions
https://github.com/Solar-Helix-Independent-Transport/allianceauth-corp-tools/releases/tag/3.0.0

**Comment by pvyParts** [comment]
https://github.com/Solar-Helix-Independent-Transport/django-eveonline-sde/issues/24
